### ISSUE TITLE
GST responses not parsed

### ISSUE THREAD

**Issue by richli** [bwolf/gpsd_proto#3]
Similar to #1, GST responses are not parsed. I'll submit a pull request shortly.

```
[2019-07-14T00:16:41Z TRACE gpsd_proto] {"class":"GST","device":"/dev/ttyAMA0","time":"2019-07-14T00:44:02.000Z","rms":5947882.000,"lat":16.000,"lon":11.000,"alt":18.000}

thread '<unnamed>' panicked at 'Unexpected gpsd data: JsonError(Error("unknown variant `GST`, expected one of `DEVICE`, `TPV`, `SKY`, `PPS`", line: 1, column: 14))', src/libcore/result.rs:997:5
```

These started getting emitted after I updated `gpsd` from 3.16 to 3.17.

**Comment by bwolf** [comment]
Any PR is welcome to fix this. I'm still on 3.16 currently.

**Comment by richli** [comment]
I opened #4 to address this

**Comment by bwolf** [comment]
Merged, thanks for the PR. Integrated in Release 0.5.0, published on crates.io.
